name: serien
description: "Verzeichnen von angeschaute und interessante Serien"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_ce_generator: ^1.8.2
  build_runner: ^2.4.15
flutter:
  uses-material-design: true